---

- name: Make sure wget is present
  ansible.builtin.apt:
    name: wget
    state: present

- name: Create apt source for Proxmox bookworm 
  ansible.builtin.raw: echo "deb [arch=amd64] http://download.proxmox.com/debian/pve bookworm pve-no-subscription" > /etc/apt/sources.list.d/pve-install-repo.list

- name: Install gpg key for Proxmox bookworm
  ansible.builtin.raw: wget https://enterprise.proxmox.com/debian/proxmox-release-bookworm.gpg -O /etc/apt/trusted.gpg.d/proxmox-release-bookworm.gpg

- name: Run the equivalent of "apt-get clean" as a separate step
  apt:
    clean: yes

- name: Run the equivalent of "apt-get update" as a separate step
  ansible.builtin.apt:
    update_cache: yes

- name: Install all packages necessary for Proxmox
  ansible.builtin.apt:
    pkg:
    - proxmox-ve
    - postfix
    - open-iscsi

- name: Remove original kernel and os-prober packages
  ansible.builtin.apt:
    pkg:
    - linux-image-amd64
    - linux-image-6.1*
    - os-prober

- name: Update grub
  ansible.builtin.raw: update-grub

- name: Rawly reboot
  ansible.builtin.raw: sync; sync; shutdown -r +1

...
